
const createPreset = (code, title, description, action, type = 'error', source = 'host') => ({
    id: `${code}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    type,
    params: {
        title,
        error_code: code,
        domain: null,
        time: null,
        ray_id: null,
        client_ip: '127.0.0.1',
        more_information: { hidden: false, text: "Learn more", link: `https://httpcats.com/${code}` },
        browser_status: { status: 'ok', status_text: 'Working', location: 'You', name: 'Browser' },
        cloudflare_status: { status: 'ok', status_text: 'Working', location: 'Cloud', name: 'Cloudflare' },
        host_status: { status: (type === 'error' && source === 'host') ? 'error' : 'ok', status_text: (type === 'error' && source === 'host') ? 'Error' : 'Working', name: 'Host' },
        error_source: source,
        what_happened: `<p>${description}</p>`,
        what_can_i_do: `<p>${action}</p>`,
        perf_sec_by: { text: "Cloudflare", link: "https://www.cloudflare.com" },
    }
});

export const errorPresets = [
    // 1xx: Informational
    createPreset(100, 'Continue', "We are ready. Are you?", "Please proceed. We are listening intently.", 'error', 'host'),
    createPreset(101, 'Switching Protocols', "Changing the rules of the game.", "Upgrade your expectations.", 'error', 'host'),
    createPreset(102, 'Processing', "Still thinking...", "Patience is a virtue. We have none.", 'error', 'host'),
    createPreset(103, 'Early Hints', "Here's a spoiler.", "Preload your assets.", 'error', 'host'),

    // 2xx: Success
    createPreset(200, 'OK', "It actually worked.", "Don't touch anything, it might break.", 'error', 'host'),
    createPreset(201, 'Created', "It's a boy! Or a girl. It's a resource.", "Cherish it.", 'error', 'host'),
    createPreset(202, 'Accepted', "We'll think about it.", "Your request is in the queue. Somewhere.", 'error', 'host'),
    createPreset(203, 'Non-Authoritative Information', "I heard this from a guy who knows a guy.", "Trust me, bro.", 'error', 'host'),
    createPreset(204, 'No Content', "The void stares back.", "Enjoy the silence.", 'error', 'host'),
    createPreset(205, 'Reset Content', "Tabula rasa.", "Refresh your perspective.", 'error', 'host'),
    createPreset(206, 'Partial Content', "Here is a piece of the puzzle.", "Collect them all.", 'error', 'host'),
    createPreset(207, 'Multi-Status', "It's complicated.", "Check the XML. If you dare.", 'error', 'host'),
    createPreset(208, 'Already Reported', "I already told you.", "Déjà vu.", 'error', 'host'),
    createPreset(218, 'This is fine', "Everything is burning, but it's fine.", "Just smile and wave.", 'error', 'host'),
    createPreset(226, 'IM Used', "I'm used.", "Recycled content is eco-friendly.", 'error', 'host'),

    // 3xx: Redirection
    createPreset(300, 'Multiple Choices', "Decisions, decisions.", "Pick a card, any card.", 'error', 'host'),
    createPreset(301, 'Moved Permanently', "It's gone. Like your motivation.", "Update your bookmarks. Or don't.", 'error', 'host'),
    createPreset(302, 'Found', "It's hiding somewhere else.", "Catch me if you can.", 'error', 'host'),
    createPreset(303, 'See Other', "Look over there!", "Distraction tactic.", 'error', 'host'),
    createPreset(304, 'Not Modified', "Same old, same old.", "If it ain't broke, don't fix it.", 'error', 'host'),
    createPreset(305, 'Use Proxy', "I'm not talking to you directly.", "Talk to my lawyer (proxy).", 'error', 'host'),
    createPreset(306, 'Switch Proxy', "The old proxy was lame.", "Upgrade your middleman.", 'error', 'host'),
    createPreset(307, 'Temporary Redirect', "Just passing through.", "Don't get too comfortable.", 'error', 'host'),
    createPreset(308, 'Permanent Redirect', "Moved to a better place.", "We're never coming back.", 'error', 'host'),

    // 4xx: Client error
    createPreset(400, 'Bad Request', "It's not me, it's you.", "Try making sense next time.", 'error', 'host'),
    createPreset(401, 'Unauthorized', "New phone, who dis?", "Login, maybe?", 'error', 'host'),
    createPreset(402, 'Payment Required', "Show me the money.", "No free lunch.", 'error', 'host'),
    createPreset(403, 'Forbidden', "You shall not pass!", "Go away.", 'error', 'host'),
    createPreset(404, 'Not Found', "I looked everywhere. Even under the couch.", "It's gone. Forever.", 'error', 'host'),
    createPreset(405, 'Method Not Allowed', "Don't do that.", "Method acting is not allowed here.", 'error', 'host'),
    createPreset(406, 'Not Acceptable', "I have standards.", "Be better.", 'error', 'host'),
    createPreset(407, 'Proxy Authentication Required', "The bouncer needs a tip.", "Pay the toll.", 'error', 'host'),
    createPreset(408, 'Request Timeout', "I got bored waiting.", "Type faster.", 'error', 'host'),
    createPreset(409, 'Conflict', "We have a problem.", "Agree to disagree.", 'error', 'host'),
    createPreset(410, 'Gone', "History is written by the victors.", "It's ancient history now.", 'error', 'host'),
    createPreset(411, 'Length Required', "Size matters.", "Tell me how long it is.", 'error', 'host'),
    createPreset(412, 'Precondition Failed', "You promised.", "Conditions were not met.", 'error', 'host'),
    createPreset(413, 'Payload Too Large', "That's what she said.", "Split it up.", 'error', 'host'),
    createPreset(414, 'URI Too Long', "TL;DR.", "Keep it brief.", 'error', 'host'),
    createPreset(415, 'Unsupported Media Type', "We don't do that here.", "Try PDF. Everyone loves PDF.", 'error', 'host'),
    createPreset(416, 'Range Not Satisfiable', "You're reaching.", "Stay within your limits.", 'error', 'host'),
    createPreset(417, 'Expectation Failed', "My expectations were low, but holy cow.", "Lower your standards.", 'error', 'host'),
    createPreset(418, 'I\'m a teapot', "Short and stout.", "Make tea, not war.", 'error', 'host'),
    createPreset(419, 'Page Expired', "Like milk.", "Refresh and smell the roses.", 'error', 'host'),
    createPreset(420, 'Enhance your calm', "Chill out, man.", "Take a deep breath.", 'error', 'host'),
    createPreset(421, 'Misdirected Request', "Wrong number.", "I don't know who you're looking for.", 'error', 'host'),
    createPreset(422, 'Unprocessable Entity', "Logic is sound, but I refuse.", "I just can't deal with this right now.", 'error', 'host'),
    createPreset(423, 'Locked', "Where is the key?", "Knock harder.", 'error', 'host'),
    createPreset(424, 'Failed Dependency', "Blame the other guy.", "It's a domino effect.", 'error', 'host'),
    createPreset(425, 'Too Early', "Go back to sleep.", "The worm is not for the early bird today.", 'error', 'host'),
    createPreset(426, 'Upgrade Required', "Your tech is ancient.", "Get with the times.", 'error', 'host'),
    createPreset(428, 'Precondition Required', "Say the magic word.", "You forgot something.", 'error', 'host'),
    createPreset(429, 'Too Many Requests', "Slow down, cowboy.", "You're clicking too fast.", 'error', 'host'),
    createPreset(430, 'Request Header Fields Too Large', "Ego check.", "Your headers are too big.", 'error', 'host'),
    createPreset(431, 'Request Header Fields Too Large', "Too much baggage.", "Travel light.", 'error', 'host'),
    createPreset(440, 'Login Time-out', "Time's up.", "You snoozed, you lost.", 'error', 'host'),
    createPreset(444, 'No Response', "...", "Ghosted.", 'error', 'host'),
    createPreset(449, 'Retry With', "Try again.", "With feeling this time.", 'error', 'host'),
    createPreset(450, 'Blocked by Windows Parental Controls', "Go ask your parents.", "You're grounded.", 'error', 'host'),
    createPreset(451, 'Unavailable For Legal Reasons', "My lawyer said no.", "Censored.", 'error', 'host'),
    createPreset(460, 'Client closed connection prematurely', "You hung up.", "Rude.", 'error', 'host'),
    createPreset(463, 'Too many forwarded IP addresses', "Too many cooks.", "The kitchen is crowded.", 'error', 'host'),
    createPreset(464, 'Incompatible protocol', "We don't speak the same language.", "Learn to communicate.", 'error', 'host'),
    createPreset(494, 'Request header too large', "Big head mode.", "Inflated headers.", 'error', 'host'),
    createPreset(495, 'SSL Certificate Error', "Trust issues.", "I don't trust you.", 'error', 'host'),
    createPreset(496, 'SSL Certificate Required', "Show me your ID.", "No ID, no entry.", 'error', 'host'),
    createPreset(497, 'HTTP Request Sent to HTTPS Port', "Secure your life.", "We only do secure here.", 'error', 'host'),
    createPreset(498, 'Invalid Token', "Fake ID.", "Nice try.", 'error', 'host'),
    createPreset(499, 'Client Closed Request', "You left.", "Was it something I said?", 'error', 'host'),

    // 5xx: Server error
    createPreset(500, 'Internal Server Error', "Code monkey fall down.", "We blame the intern.", 'error', 'cloudflare'),
    createPreset(501, 'Not Implemented', "I can't do that, Dave.", "Coming soon. Maybe.", 'error', 'host'),
    createPreset(502, 'Bad Gateway', "The middleman is drunk.", "Pass the buck.", 'error', 'cloudflare'),
    createPreset(503, 'Service Unavailable', "Nap time.", "The server is on a coffee break.", 'error', 'host'),
    createPreset(504, 'Gateway Timeout', "The hamster died.", "Feed the hamster.", 'error', 'cloudflare'),
    createPreset(505, 'HTTP Version Not Supported', "Too futuristic.", "We like the old ways.", 'error', 'host'),
    createPreset(506, 'Variant Also Negotiates', "We couldn't agree on anything.", "Negotiations broke down.", 'error', 'host'),
    createPreset(507, 'Insufficient Storage', "I'm full.", "No more room for dessert.", 'error', 'host'),
    createPreset(508, 'Loop Detected', "Groundhog Day.", "And again. And again.", 'error', 'host'),
    createPreset(509, 'Bandwidth Limit Exceeded', "You used all the internet.", "Go outside.", 'error', 'host'),
    createPreset(510, 'Not Extended', "I need more.", "Extensions required.", 'error', 'host'),
    createPreset(511, 'Network Authentication Required', "Login first.", "Who sent you?", 'error', 'cloudflare'),
    createPreset(520, 'Web server is returning an unknown error', "Something happened.", "We don't know what, but it's bad.", 'error', 'cloudflare'),
    createPreset(521, 'Web server is down', "It's dead, Jim.", "He's dead.", 'error', 'cloudflare'),
    createPreset(522, 'Connection timed out', "Connection timed out.", "The server is ghosting us.", 'error', 'cloudflare'),
    createPreset(523, 'Origin is unreachable', "You can't get there from here.", "Road closed.", 'error', 'cloudflare'),
    createPreset(524, 'A Timeout Occurred', "Still waiting...", "It's been 84 years...", 'error', 'cloudflare'),
    createPreset(525, 'SSL handshake failed', "Awkward greeting.", "Left hanging.", 'error', 'cloudflare'),
    createPreset(526, 'Invalid SSL certificate', "Sketchy certificate.", "Looks fake to me.", 'error', 'cloudflare'),
    createPreset(527, 'Railgun Listener to Origin', "Railgun error.", "Sounds cool, but it's broken.", 'error', 'cloudflare'),
    createPreset(529, 'The service is overloaded', "Too much love.", "We are popular.", 'error', 'host'),
    createPreset(530, 'Site Frozen', "Let it go.", "Frozen in time.", 'error', 'cloudflare'),
    createPreset(561, 'Unauthorized', "Access denied by the other guy.", "Not my fault.", 'error', 'cloudflare'),
    createPreset(598, 'Network read timeout error', "I can't read this.", "Illiterate network.", 'error', 'cloudflare'),
    createPreset(599, 'Network Connect Timeout Error', "I can't connect.", "Lonely network.", 'error', 'cloudflare'),

    // Other
    createPreset(999, 'Request Denied', "No. Just no.", "Don't ask again.", 'error', 'cloudflare'),
];

export const successPreset = {
    id: 'success-easter-egg',
    type: 'success',
    params: {
        title: 'Welcome!',
        error_code: 200,
    }
};

export const allPresets = [...errorPresets, successPreset];
